languageCode = "en-us"
title = "Taihon's thoughts"
baseurl = "https://taihon.github.io/"
theme = "hyde"

[params]
themeColor = "theme-base-0d"
layoutReverse = true
description = "My thoughts about System Administration, Programming, and IT in general."
disqusShortname = "taihon"
SectionPagesMenu = "main"